-- Create the database if it does not exist
CREATE DATABASE IF NOT EXISTS WEATHER_DATA;

-- Create the schema if it does not exist
CREATE SCHEMA IF NOT EXISTS WEATHER_DATA.POC_STAGING;

-- Create the transient table
CREATE OR REPLACE TRANSIENT TABLE WEATHER_DATA.POC_STAGING.WEATHER_RAW (
    LAT FLOAT,
    LON FLOAT,
    VALIDDATE TIMESTAMP_TZ(9),
    T_2M FLOAT,
    PRECIP_1H FLOAT,
    RELATIVE_HUMIDITY_2M FLOAT,
    MSL_PRESSURE FLOAT,
    DEW_POINT_2M FLOAT,
    WIND_SPEED_2M FLOAT,
    TOTAL_CLOUD_COVER FLOAT,
    WEATHER_SYMBOL_1H NUMBER(38, 0),
    T_2M_UNIT VARCHAR(16777216),
    PRECIP_1H_UNIT VARCHAR(16777216),
    RELATIVE_HUMIDITY_2M_UNIT VARCHAR(16777216),
    MSL_PRESSURE_UNIT VARCHAR(16777216),
    DEW_POINT_2M_UNIT VARCHAR(16777216),
    WIND_SPEED_2M_UNIT VARCHAR(16777216),
    TOTAL_CLOUD_COVER_UNIT VARCHAR(16777216),
    LOAD_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);